version: '3'

services:
  client:
    build: ./client
    container_name: bart.client
    volumes:
      - ../../client:/var/www/app

  api:
    build: ./api
    container_name: bart.api
    depends_on:
      - postgres
    volumes:
      - ../../api:/var/www/app
      - ${SSH_KEY_PATH:-~/.ssh}:/root/.ssh:ro

  reverse_proxy:
    image: caddy:2.7-alpine
    container_name: bart.caddy
    restart: unless-stopped
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  postgres:
    image: postgres:15
    container_name: bart.db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
