api_platform:
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
        html: ['text/html']
    defaults:
    # Rely on session authentication
        stateless: false
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
        pagination_items_per_page: 10
        pagination_maximum_items_per_page: 50
    event_listeners_backward_compatibility_layer: false
    keep_legacy_inflector: false

when@prod:
    api_platform:
        enable_swagger_ui: false
